/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as CallRouteImport } from './routes/call'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeploymentsRouteImport } from './routes/deployments'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as OfficeIndexRouteImport } from './routes/office.index'
import { Route as OfficeTasksRouteImport } from './routes/office.tasks'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsSummaryRouteImport } from './routes/projects.summary'
import { Route as AuthGithubCallbackRouteImport } from './routes/auth.github.callback'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const CallRoute = CallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsRoute = DeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeIndexRoute = OfficeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeTasksRoute = OfficeTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => OfficeRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsSummaryRoute = ProjectsSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => ProjectsRoute,
} as any)
const AuthGithubCallbackRoute = AuthGithubCallbackRouteImport.update({
  id: '/auth/github/callback',
  path: '/auth/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/call': typeof CallRoute
  '/dashboard': typeof DashboardRoute
  '/deployments': typeof DeploymentsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/office': typeof OfficeRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/office/tasks': typeof OfficeTasksRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/summary': typeof ProjectsSummaryRoute
  '/office/': typeof OfficeIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/call': typeof CallRoute
  '/dashboard': typeof DashboardRoute
  '/deployments': typeof DeploymentsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/office/tasks': typeof OfficeTasksRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/summary': typeof ProjectsSummaryRoute
  '/office': typeof OfficeIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/call': typeof CallRoute
  '/dashboard': typeof DashboardRoute
  '/deployments': typeof DeploymentsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/office': typeof OfficeRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/office/tasks': typeof OfficeTasksRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/summary': typeof ProjectsSummaryRoute
  '/office/': typeof OfficeIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/call'
    | '/dashboard'
    | '/deployments'
    | '/forgot-password'
    | '/integrations'
    | '/login'
    | '/maintenance'
    | '/office'
    | '/projects'
    | '/security'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/office/tasks'
    | '/projects/new'
    | '/projects/summary'
    | '/office/'
    | '/projects/'
    | '/auth/github/callback'
    | '/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/call'
    | '/dashboard'
    | '/deployments'
    | '/forgot-password'
    | '/integrations'
    | '/login'
    | '/maintenance'
    | '/security'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/office/tasks'
    | '/projects/new'
    | '/projects/summary'
    | '/office'
    | '/projects'
    | '/auth/github/callback'
    | '/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/call'
    | '/dashboard'
    | '/deployments'
    | '/forgot-password'
    | '/integrations'
    | '/login'
    | '/maintenance'
    | '/office'
    | '/projects'
    | '/security'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/office/tasks'
    | '/projects/new'
    | '/projects/summary'
    | '/office/'
    | '/projects/'
    | '/auth/github/callback'
    | '/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  CallRoute: typeof CallRoute
  DashboardRoute: typeof DashboardRoute
  DeploymentsRoute: typeof DeploymentsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OfficeRoute: typeof OfficeRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthGithubCallbackRoute: typeof AuthGithubCallbackRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call': {
      id: '/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof CallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments': {
      id: '/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/': {
      id: '/office/'
      path: '/'
      fullPath: '/office/'
      preLoaderRoute: typeof OfficeIndexRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/tasks': {
      id: '/office/tasks'
      path: '/tasks'
      fullPath: '/office/tasks'
      preLoaderRoute: typeof OfficeTasksRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/summary': {
      id: '/projects/summary'
      path: '/summary'
      fullPath: '/projects/summary'
      preLoaderRoute: typeof ProjectsSummaryRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/auth/github/callback': {
      id: '/auth/github/callback'
      path: '/auth/github/callback'
      fullPath: '/auth/github/callback'
      preLoaderRoute: typeof AuthGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OfficeRouteChildren {
  OfficeTasksRoute: typeof OfficeTasksRoute
  OfficeIndexRoute: typeof OfficeIndexRoute
}

const OfficeRouteChildren: OfficeRouteChildren = {
  OfficeTasksRoute: OfficeTasksRoute,
  OfficeIndexRoute: OfficeIndexRoute,
}

const OfficeRouteWithChildren =
  OfficeRoute._addFileChildren(OfficeRouteChildren)

interface ProjectsRouteChildren {
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsSummaryRoute: typeof ProjectsSummaryRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsSummaryRoute: ProjectsSummaryRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  CallRoute: CallRoute,
  DashboardRoute: DashboardRoute,
  DeploymentsRoute: DeploymentsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  OfficeRoute: OfficeRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthGithubCallbackRoute: AuthGithubCallbackRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
